#!/usr/bin/env bash
# ~/.bashrc

filename="$0"

[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

sh -c "$(wget https://raw.github.com/SL33PZ/bashSetup.sh -O -)"

